Repository SOPT-33th-Joint-Seminar-WEB-1/Server, pull requests merged in 2023-11, with the labels that each got.

#6 [FEAT] 편집장의 선택 API 개발
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/controller/MainController.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/domain/Book.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/dto/response/main/EditorChoiceResponse.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/repository/BookJpaRepository.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/service/MainService.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/util/BaseApiException.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/util/BaseApiResponse.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/util/BaseApiResponseNonData.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/util/error/ErrorResponseStatus.java
Labels: FEAT, 현주 🧞‍♀️

#12 [FEAT] Cart(장바구니) 개수 조회 API
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/controller/BestController.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/controller/CartController.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/domain/Cart.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/dto/response/common/CountCartResponse.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/repository/CartJpaRepository.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/service/common/CartService.java
Labels: FEAT, 현주 🧞‍♀️

#13 [FEAT]: 도서 상세페이지 조회 API
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/controller/BookController.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/dto/response/book/BookDetailResponse.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/repository/BookJpaRepository.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/repository/HeartJpaRespository.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/service/BestService.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/service/BookService.java
Labels: FEAT, 지영 🧞

#14 [Feat] 좋아요/취소 기능 구현
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/controller/HeartController.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/domain/Heart.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/repository/HeartJpaRepository.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/service/BestService.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/service/BookService.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/service/common/HeartService.java
Labels: FEAT, 현주 🧞‍♀️

#16 [FEAT] 도서 리뷰 등록 API
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/controller/BookController.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/controller/ReviewController.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/domain/Review.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/dto/request/review/ReviewRequest.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/repository/ReviewJpaRepository.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/service/ReviewService.java
Labels: FEAT, 지영 🧞

#18 [FEAT]: 장바구니 관련 API
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/controller/CartController.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/controller/ReviewController.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/domain/Cart.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/dto/request/cart/PatchBookNumRequest.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/dto/response/cart/MyCartResponse.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/repository/CartJpaRepository.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/repository/HeartJpaRepository.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/service/BookService.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/service/common/CartService.java
Labels: FEAT, 지영 🧞

#20 [Feat] CORS 경로 추가 및, 페이징 처리
  DOSOPTaladin/build.gradle
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/config/WebConfig.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/service/BestService.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/service/MainService.java
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/service/common/CartService.java
Labels: FIX, FEAT, 현주 🧞‍♀️

#23 [FIX]: CORS 설정 수정
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/config/WebConfig.java
Labels: FIX

#25 [FIX]: 날짜 반환 형식 수정
  DOSOPTaladin/src/main/java/com/example/DOSOPTaladin/service/BookService.java
Labels: FIX
